"""Generate the v0.9 capstone synthesis notebook (#228).

Mirrors the generator-script convention used by the v0.6–v0.8 notebooks: this
script emits the deterministic ``.ipynb`` JSON so the notebook content is
reproducible and reviewable as code. Regeneration is optional and manual — the
committed ``.ipynb`` is authoritative.

The synthesis notebook reuses — does NOT reimplement — the v0.6 graph layer,
the v0.8 production-monitoring builders, and the v0.7 governance template. It
runs BOTH tracks in one comparison frame: graph/case evidence as investigative
support, the v0.8 monitoring flow on the capstone scores, and a governance memo
synthesising both tracks.

Run from the repo root::

    uv run python notebooks/09_capstone/_build_capstone_synthesis_notebook.py
"""

from __future__ import annotations

import json
from pathlib import Path

NOTEBOOK_DIR = Path(__file__).resolve().parent
NOTEBOOK_PATH = NOTEBOOK_DIR / "capstone_synthesis.ipynb"


def _md(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source.splitlines(keepends=True)}


def _code(source: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }


CELLS = [
    _md(
        "# Capstone Synthesis: Graph Evidence, Production Monitoring, And Governance\n"
        "\n"
        "This is the v0.9 capstone **synthesis** notebook. It closes the end-to-end path the "
        "scenario briefs call for: it pulls graph/case evidence into the alert review, runs the "
        "v0.8 production-monitoring flow on the capstone scores for BOTH **Fraud detection "
        "tracks**, and renders a governance memo synthesising both tracks.\n"
        "\n"
        "It reuses — does NOT reimplement — the v0.6 graph layer "
        "(`circular_funds_movement` for **Alpine Crest Private Bank**, `mule_ring` for "
        "**NovaBank Digital**), the v0.8 monitoring builders (`run_batch_scoring`, "
        "`decide_alerts`, `record_reviewer_action`, `inspect_alert_queue`, "
        "`check_score_drift`), and the v0.7 governance template (`build_model_documentation`, "
        "`build_monitoring_checklist`). Graph evidence and case-library links are presented as "
        "**investigative support**, not a replacement for the tabular score from the capstone "
        "scoring notebooks.\n"
        "\n"
        "Learning goal: see the integrated path end to end — brief → data → features → score → "
        "alerts → graph evidence → monitoring → governance memo — while keeping the limitation-"
        "aware framing visible. **A model should not be judged by headline accuracy.**\n"
        "\n"
        "> Educational exercise on synthetic data. No real Client, account, or transaction "
        "data; no certification or legal-advice claim. The repository is pre-publication; v0.9 "
        "is a beta review point."
    ),
    _md(
        "## 1. Build Both Tracks' Capstone Scores\n"
        "\n"
        "Generate the capstone substrate for both tracks, build the engineered feature frame, "
        "and fit the same reproducible baseline used in the capstone scoring notebooks. The "
        "scored model frames feed the monitoring flow and the graph layer below. Each track "
        "builds on the v0.9 capstone dataset (#225)."
    ),
    _code(
        "import pandas as pd\n"
        "from sklearn.compose import ColumnTransformer\n"
        "from sklearn.linear_model import LogisticRegression\n"
        "from sklearn.pipeline import Pipeline\n"
        "from sklearn.preprocessing import StandardScaler\n"
        "\n"
        "from banking_fraud_lab import (\n"
        "    build_banking_graph,\n"
        "    build_all_graph_features,\n"
        "    build_digital_banking_features,\n"
        "    build_learner_facing_views,\n"
        "    build_model_documentation,\n"
        "    build_monitoring_checklist,\n"
        "    build_private_banking_features,\n"
        "    evaluate_alert_scores,\n"
        "    generate_capstone_digital_banking_world,\n"
        "    generate_capstone_private_banking_world,\n"
        "    join_graph_features_to_view,\n"
        "    recommend_lowest_cost_threshold,\n"
        ")\n"
        "from banking_fraud_lab.features import (\n"
        "    DIGITAL_BANKING_FEATURE_FAMILIES,\n"
        "    PRIVATE_BANKING_FEATURE_FAMILIES,\n"
        ")\n"
        "from banking_fraud_lab.monitoring import (\n"
        "    check_score_drift,\n"
        "    decide_alerts,\n"
        "    inspect_alert_queue,\n"
        "    record_reviewer_action,\n"
        "    run_batch_scoring,\n"
        "    summarise_alert_operations,\n"
        ")\n"
        "\n"
        "pd.set_option(\"display.max_columns\", 40)"
    ),
    _code(
        "def _fit_track(tables, build_features, feature_families, *, join_keys):\n"
        "    learner_tables = build_learner_facing_views(tables)\n"
        "    feature_frame = build_features(learner_tables)\n"
        "    model_frame = (\n"
        "        learner_tables[\"cases\"][\n"
        "            [\"case_id\", \"alert_id\", \"transaction_id\", \"banking_relationship_id\"]\n"
        "        ]\n"
        "        .merge(\n"
        "            learner_tables[\"alerts\"][[\"alert_id\", \"alert_type\", \"severity\"]],\n"
        "            on=\"alert_id\",\n"
        "            how=\"inner\",\n"
        "            validate=\"one_to_one\",\n"
        "        )\n"
        "        .merge(\n"
        "            learner_tables[\"case_outcomes\"][[\n"
        "                \"case_id\", \"confirmed_fraud\", \"loss_amount_chf\"\n"
        "            ]],\n"
        "            on=\"case_id\",\n"
        "            how=\"inner\",\n"
        "            validate=\"one_to_one\",\n"
        "        )\n"
        "        .merge(feature_frame, on=join_keys, how=\"inner\", validate=\"one_to_one\")\n"
        "    )\n"
        "    assert model_frame[\"confirmed_fraud\"].nunique() == 2\n"
        "    feature_output_columns = [\n"
        "        column\n"
        "        for spec in feature_families\n"
        "        for column in spec.output_columns\n"
        "    ]\n"
        "    numeric_feature_columns = [\n"
        "        column\n"
        "        for column in feature_output_columns\n"
        "        if pd.api.types.is_numeric_dtype(model_frame[column])\n"
        "    ]\n"
        "    preprocess = ColumnTransformer(\n"
        "        [(\"numeric\", StandardScaler(), numeric_feature_columns)],\n"
        "        remainder=\"drop\",\n"
        "    )\n"
        "    model = Pipeline(\n"
        "        [\n"
        "            (\"preprocess\", preprocess),\n"
        "            (\n"
        "                \"model\",\n"
        "                LogisticRegression(\n"
        "                    random_state=42,\n"
        "                    solver=\"lbfgs\",\n"
        "                    max_iter=1000,\n"
        "                    class_weight=\"balanced\",\n"
        "                ),\n"
        "            ),\n"
        "        ]\n"
        "    )\n"
        "    target = model_frame[\"confirmed_fraud\"].astype(bool)\n"
        "    model.fit(model_frame[numeric_feature_columns], target)\n"
        "    model_frame = model_frame.assign(\n"
        "        score=model.predict_proba(model_frame[numeric_feature_columns])[:, 1].round(6)\n"
        "    )\n"
        "    return {\n"
        "        \"learner_tables\": learner_tables,\n"
        "        \"tables\": tables,\n"
        "        \"model\": model,\n"
        "        \"model_frame\": model_frame,\n"
        "        \"numeric_feature_columns\": numeric_feature_columns,\n"
        "    }\n"
        "\n"
        "\n"
        "pb = _fit_track(\n"
        "    generate_capstone_private_banking_world(seed=42),\n"
        "    build_private_banking_features,\n"
        "    PRIVATE_BANKING_FEATURE_FAMILIES,\n"
        "    join_keys=[\"transaction_id\", \"banking_relationship_id\"],\n"
        ")\n"
        "db = _fit_track(\n"
        "    generate_capstone_digital_banking_world(seed=42),\n"
        "    build_digital_banking_features,\n"
        "    DIGITAL_BANKING_FEATURE_FAMILIES,\n"
        "    join_keys=[\"transaction_id\"],\n"
        ")\n"
        "pb[\"model_frame\"].attrs[\"institution\"] = \"Alpine Crest Private Bank\"\n"
        "db[\"model_frame\"].attrs[\"institution\"] = \"NovaBank Digital\"\n"
        "\n"
        "score_overview = pd.DataFrame(\n"
        "    [\n"
        "        {\n"
        "            \"track\": \"Alpine Crest Private Bank\",\n"
        "            \"scored_alerts\": len(pb[\"model_frame\"]),\n"
        "        },\n"
        "        {\n"
        "            \"track\": \"NovaBank Digital\",\n"
        "            \"scored_alerts\": len(db[\"model_frame\"]),\n"
        "        },\n"
        "    ]\n"
        ")\n"
        "score_overview"
    ),
    _md(
        "## 2. Graph Evidence As Investigative Support\n"
        "\n"
        "The v0.6 graph layer builds a NetworkX graph from the capstone tables and derives graph "
        "features that the tabular score does not capture. For **Alpine Crest Private Bank** the "
        "investigation target is `circular_funds_movement`; for **NovaBank Digital** it is "
        "`mule_ring`. Graph evidence is joined back to the alert view so a reviewer sees the "
        "network context behind an alert — but it is **investigative support, not a score "
        "replacement**. Case-library source packs (`circular-funds-movement`, "
        "`graph-network-money-mules`) add the public-facts anchor."
    ),
    _code(
        "def _graph_alert_context(tables, model_frame, *, family_id):\n"
        "    graph = build_banking_graph(tables)\n"
        "    graph_features = build_all_graph_features(graph)\n"
        "    family_frame = graph_features[family_id]\n"
        "    alert_view = model_frame[\n"
        "        [\"alert_id\", \"banking_relationship_id\", \"transaction_id\", \"alert_type\", \"score\"]\n"
        "    ].head(8)\n"
        "    augmented = join_graph_features_to_view(family_frame, alert_view)\n"
        "    return augmented\n"
        "\n"
        "\n"
        "# circular_funds_movement is the target of the centrality/community/path/bridge families.\n"
        "pb_graph_context = _graph_alert_context(\n"
        "    pb[\"tables\"], pb[\"model_frame\"], family_id=\"graph_centrality\"\n"
        ")\n"
        "# mule_ring is the target of the connected-component/degree families.\n"
        "db_graph_context = _graph_alert_context(\n"
        "    db[\"tables\"], db[\"model_frame\"], family_id=\"graph_connected_component\"\n"
        ")\n"
        "\n"
        "graph_evidence = pd.DataFrame(\n"
        "    [\n"
        "        {\n"
        "            \"track\": \"Alpine Crest Private Bank\",\n"
        "            \"detection_pattern\": \"circular_funds_movement\",\n"
        "            \"graph_family\": \"graph_centrality\",\n"
        "            \"alerts_with_graph_context\": len(pb_graph_context),\n"
        "        },\n"
        "        {\n"
        "            \"track\": \"NovaBank Digital\",\n"
        "            \"detection_pattern\": \"mule_ring\",\n"
        "            \"graph_family\": \"graph_connected_component\",\n"
        "            \"alerts_with_graph_context\": len(db_graph_context),\n"
        "        },\n"
        "    ]\n"
        ")\n"
        "graph_evidence"
    ),
    _md(
        "## 3. Production Monitoring Flow\n"
        "\n"
        "For each track, source the threshold from the v0.7 capacity-aware recommender, run "
        "batch scoring, decide alerts, summarise operations with a reused `evaluate_alert_scores` "
        "result, record a reviewer action on the top alert, inspect the alert queue, and run a "
        "score-drift check. Each track's monitoring artifacts live in its own flow dict."
    ),
    _code(
        "def _threshold_for(model_frame, case_outcomes):\n"
        "    alert_scores = pd.DataFrame(\n"
        "        {\"alert_id\": model_frame[\"alert_id\"], \"score\": model_frame[\"score\"]}\n"
        "    )\n"
        "    recommendation = recommend_lowest_cost_threshold(\n"
        "        cases=model_frame[[\"case_id\", \"alert_id\"]],\n"
        "        case_outcomes=case_outcomes,\n"
        "        alert_scores=alert_scores,\n"
        "        candidate_thresholds=(0.25, 0.5, 0.75),\n"
        "        alert_capacities=(5, 10, 25),\n"
        "        investigation_cost_chf=75.0,\n"
        "        false_positive_cost_chf=25.0,\n"
        "        missed_fraud_cost_chf=1_000.0,\n"
        "    )\n"
        "    return float(recommendation[\"recommended_threshold\"])\n"
        "\n"
        "\n"
        "def _monitor(track, *, detection_pattern_id, scorer, score_lineage):\n"
        "    model_frame = track[\"model_frame\"]\n"
        "    learner_tables = track[\"learner_tables\"]\n"
        "    case_outcomes = learner_tables[\"case_outcomes\"]\n"
        "    alert_scores = pd.DataFrame(\n"
        "        {\"alert_id\": model_frame[\"alert_id\"], \"score\": model_frame[\"score\"]}\n"
        "    )\n"
        "    threshold = _threshold_for(model_frame, case_outcomes)\n"
        "    batch = run_batch_scoring(\n"
        "        model_frame[score_lineage].copy(),\n"
        "        detection_pattern_id=detection_pattern_id,\n"
        "        threshold=threshold,\n"
        "        scorer=scorer,\n"
        "        score_version=\"0.8.0\",\n"
        "        evidence_ref=\"v0.7 recommend_lowest_cost_threshold\",\n"
        "    )\n"
        "    threshold_id = str(batch.threshold_rows[\"threshold_id\"].iloc[0])\n"
        "    decisions = decide_alerts(\n"
        "        batch.score_rows, threshold=threshold, threshold_id=threshold_id\n"
        "    )\n"
        "    operations_input = decisions.alert_decision_rows.merge(\n"
        "        learner_tables[\"alerts\"][[\"alert_id\", \"alert_status\", \"severity\", \"generated_at\"]],\n"
        "        on=\"alert_id\",\n"
        "        how=\"inner\",\n"
        "        validate=\"many_to_one\",\n"
        "    )\n"
        "    operations_input[\"institution_name\"] = model_frame.attrs.get(\"institution\", \"\")\n"
        "    evaluation = evaluate_alert_scores(\n"
        "        cases=model_frame[[\"case_id\", \"alert_id\"]],\n"
        "        case_outcomes=case_outcomes,\n"
        "        alert_scores=alert_scores,\n"
        "        thresholds=(threshold,),\n"
        "        alert_capacity=10,\n"
        "        investigation_cost_chf=75.0,\n"
        "        false_positive_cost_chf=25.0,\n"
        "        missed_fraud_cost_chf=1_000.0,\n"
        "    )\n"
        "    operations = summarise_alert_operations(\n"
        "        operations_input, alert_capacity=10, evaluation=evaluation\n"
        "    )\n"
        "    alerted = decisions.alert_decision_rows[\n"
        "        decisions.alert_decision_rows[\"decision\"] == \"alert\"\n"
        "    ]\n"
        "    reviewer_action = None\n"
        "    if not alerted.empty:\n"
        "        reviewer_action = record_reviewer_action(\n"
        "            alerted.head(1),\n"
        "            reviewer=\"capstone-reviewer\",\n"
        "            action=\"open_case\",\n"
        "            rationale=\"Capstone synthesis review combining score and graph evidence.\",\n"
        "            evidence={\"graph_family\": \"investigative_support\"},\n"
        "        )\n"
        "    queue = inspect_alert_queue(\n"
        "        operations_input, institution=model_frame.attrs.get(\"institution\", \"\")\n"
        "    )\n"
        "    reference_scores = batch.score_rows[\"score\"]\n"
        "    review_scores = (reference_scores + 0.2).clip(upper=1.0)\n"
        "    drift = check_score_drift(reference_scores, review_scores, tolerance=0.05)\n"
        "    return {\n"
        "        \"threshold\": threshold,\n"
        "        \"batch\": batch,\n"
        "        \"decisions\": decisions,\n"
        "        \"operations\": operations,\n"
        "        \"evaluation\": evaluation,\n"
        "        \"reviewer_action\": reviewer_action,\n"
        "        \"queue\": queue,\n"
        "        \"drift\": drift,\n"
        "    }\n"
        "\n"
        "\n"
        "pb_flow = _monitor(\n"
        "    pb,\n"
        "    detection_pattern_id=\"pb_high_value_movement\",\n"
        "    scorer=\"alpine-crest-capstone\",\n"
        "    score_lineage=[\"score\", \"banking_relationship_id\", \"transaction_id\", \"alert_id\"],\n"
        ")\n"
        "db_flow = _monitor(\n"
        "    db,\n"
        "    detection_pattern_id=\"digital_scam_to_mule\",\n"
        "    scorer=\"novabank-capstone\",\n"
        "    score_lineage=[\"score\", \"banking_relationship_id\", \"transaction_id\", \"alert_id\"],\n"
        ")\n"
        "\n"
        "monitoring_overview = pd.DataFrame(\n"
        "    [\n"
        "        {\n"
        "            \"institution\": \"Alpine Crest Private Bank\",\n"
        "            \"threshold\": pb_flow[\"threshold\"],\n"
        "            \"alert_volume\": pb_flow[\"operations\"][\"alert_volume\"],\n"
        "            \"score_drift\": pb_flow[\"drift\"].drifted,\n"
        "        },\n"
        "        {\n"
        "            \"institution\": \"NovaBank Digital\",\n"
        "            \"threshold\": db_flow[\"threshold\"],\n"
        "            \"alert_volume\": db_flow[\"operations\"][\"alert_volume\"],\n"
        "            \"score_drift\": db_flow[\"drift\"].drifted,\n"
        "        },\n"
        "    ]\n"
        ")\n"
        "monitoring_overview"
    ),
    _md(
        "## 4. Governance Memo (Both Tracks)\n"
        "\n"
        "Reuse the v0.7 governance framing — `build_model_documentation` and "
        "`build_monitoring_checklist` for each track — alongside the monitoring outputs and graph "
        "evidence. The memo synthesises both tracks, ties monitoring back to the Alert lifecycle, "
        "and explicitly avoids headline accuracy claims. This memo cross-references "
        "`03_alert_governance` and `07_interpretability_model_risk` rather than duplicating them."
    ),
    _code(
        "pb_documentation = build_model_documentation(\n"
        "    pb[\"model\"],\n"
        "    institution=\"Alpine Crest Private Bank\",\n"
        "    detection_pattern_id=\"pb_high_value_movement\",\n"
        "    feature_columns=pb[\"numeric_feature_columns\"],\n"
        "    model_frame=pb[\"model_frame\"],\n"
        "    seed=42,\n"
        "    cost_parameters={\n"
        "        \"investigation_cost_chf\": 75.0,\n"
        "        \"false_positive_cost_chf\": 25.0,\n"
        "        \"missed_fraud_cost_chf\": 1_000.0,\n"
        "    },\n"
        ")\n"
        "db_documentation = build_model_documentation(\n"
        "    db[\"model\"],\n"
        "    institution=\"NovaBank Digital\",\n"
        "    detection_pattern_id=\"digital_scam_to_mule\",\n"
        "    feature_columns=db[\"numeric_feature_columns\"],\n"
        "    model_frame=db[\"model_frame\"],\n"
        "    seed=42,\n"
        "    cost_parameters={\n"
        "        \"investigation_cost_chf\": 75.0,\n"
        "        \"false_positive_cost_chf\": 25.0,\n"
        "        \"missed_fraud_cost_chf\": 1_000.0,\n"
        "    },\n"
        ")\n"
        "pb_checklist = build_monitoring_checklist(\n"
        "    institution=\"Alpine Crest Private Bank\",\n"
        "    detection_pattern_id=\"pb_high_value_movement\",\n"
        "    evaluation=pb_flow[\"evaluation\"],\n"
        ")\n"
        "db_checklist = build_monitoring_checklist(\n"
        "    institution=\"NovaBank Digital\",\n"
        "    detection_pattern_id=\"digital_scam_to_mule\",\n"
        "    evaluation=db_flow[\"evaluation\"],\n"
        ")\n"
        "\n"
        "memo = [\n"
        "    \"# Capstone Governance Memo (Synthetic Data)\",\n"
        "    \"\",\n"
        "    \"Educational exercise only — not legal, compliance, or professional advice.\",\n"
        "    \"\",\n"
        "    \"## Alpine Crest Private Bank — private_banking\",\n"
        "    \"- Detection pattern: pb_high_value_movement / circular_funds_movement (graph support)\",\n"
        "    f\"- Threshold: {pb_flow['threshold']:.2f} (v0.7 capacity-aware recommender)\",\n"
        "    f\"- Alert volume: {pb_flow['operations']['alert_volume']} / capacity 10\",\n"
        "    f\"- Precision {pb_flow['operations']['precision']:.2f}, recall {pb_flow['operations']['recall']:.2f}\",\n"
        "    f\"- Score drift flagged: {pb_flow['drift'].drifted} (review prompt, not a verdict)\",\n"
        "    f\"- Documentation sections filled: {len(pb_documentation['sections'])}\",\n"
        "    \"\",\n"
        "    \"## NovaBank Digital — digital_banking\",\n"
        "    \"- Detection pattern: digital_scam_to_mule / mule_ring (graph support)\",\n"
        "    f\"- Threshold: {db_flow['threshold']:.2f} (v0.7 capacity-aware recommender)\",\n"
        "    f\"- Alert volume: {db_flow['operations']['alert_volume']} / capacity 10\",\n"
        "    f\"- Precision {db_flow['operations']['precision']:.2f}, recall {db_flow['operations']['recall']:.2f}\",\n"
        "    f\"- Score drift flagged: {db_flow['drift'].drifted} (review prompt, not a verdict)\",\n"
        "    f\"- Documentation sections filled: {len(db_documentation['sections'])}\",\n"
        "    \"\",\n"
        "    \"## Alert lifecycle mapping\",\n"
        "    \"- score → run_batch_scoring; alert_decision → decide_alerts; \"\n"
        "    \"reviewer_action → record_reviewer_action; queue → inspect_alert_queue; \"\n"
        "    \"drift → check_score_drift.\",\n"
        "    \"- Graph evidence (circular_funds_movement / mule_ring) is investigative support, \"\n"
        "    \"not a score replacement.\",\n"
        "    \"- See 03_alert_governance and 07_interpretability_model_risk for the deeper \"\n"
        "    \"governance and interpretability treatment.\",\n"
        "    \"\",\n"
        "    \"**A model should not be judged by headline accuracy.** Protected answer keys stay \"\n"
        "    \"separate from learner-facing data; alert outcomes are operational decisions.\",\n"
        "]\n"
        "print(\"\\n\".join(memo))"
    ),
    _md(
        "## Capstone Takeaways\n"
        "\n"
        "This synthesis notebook closed the v0.9 capstone loop: capstone scores from both "
        "tracks, graph evidence (`circular_funds_movement` / `mule_ring`) as investigative "
        "support, the v0.8 production-monitoring flow (batch scoring → decisions → reviewer "
        "action → alert queue → drift), and a governance memo synthesising both tracks via the "
        "v0.7 documentation and monitoring-checklist templates. The integrated path the PRD calls "
        "for — brief → data → SQL → features → model → alerts → graph evidence → monitoring → "
        "governance memo — is now visible end to end.\n"
        "\n"
        "**A model should not be judged by headline accuracy.**"
    ),
]


def build_notebook() -> dict:
    """Assemble the notebook JSON."""
    return {
        "cells": CELLS,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    """Write the notebook to disk under notebooks/09_capstone/."""
    NOTEBOOK_DIR.mkdir(parents=True, exist_ok=True)
    NOTEBOOK_PATH.write_text(
        json.dumps(build_notebook(), indent=1, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {NOTEBOOK_PATH} ({len(CELLS)} cells)")


if __name__ == "__main__":
    main()
