"""Generate the v0.8 alert-review + governance notebook (#209).

Mirrors the generator-script convention used by the Alpine Crest (#207) and
NovaBank (#208) monitoring notebooks: this script emits the deterministic
``.ipynb`` JSON so the notebook content is reproducible and reviewable as code.
Regeneration is optional and manual — the committed ``.ipynb`` is authoritative.

This notebook closes the v0.8 loop: it runs BOTH tracks' monitoring flow side
by side (Alpine Crest Private Bank and NovaBank Digital), contrasts their
alert-volume / precision / recall / capacity / closure / drift behaviour in one
comparison frame, runs an alert-review exercise that reuses a v0.7
``explain_feature_family`` summary as reviewer-action evidence and walks the
audit-event lineage back to Banking relationship / Client-or-User / Detection
pattern, and renders a governance-readable summary that ties monitoring outputs
back to the v0.7 monitoring-checklist dimensions and the Alert lifecycle.

Run from the repo root::

    uv run python notebooks/08_production_monitoring_patterns/_build_alert_review_governance_notebook.py
"""

from __future__ import annotations

import json
from pathlib import Path

# Resolve relative to this script so it works regardless of cwd.
NOTEBOOK_DIR = Path(__file__).resolve().parent
NOTEBOOK_PATH = NOTEBOOK_DIR / "alert_review_governance.ipynb"


def _md(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source.splitlines(keepends=True)}


def _code(source: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }


CELLS = [
    _md(
        "# Alert Review And Governance: Track Comparison\n"
        "\n"
        "This is the v0.8 capstone monitoring notebook. It **contrasts** the two "
        "first-class fraud-detection tracks side by side — **Alpine Crest Private "
        "Bank** (private banking, `pb_high_value_movement`) and **NovaBank "
        "Digital** (digital banking, `digital_scam_to_mule`) — by running each "
        "track's full v0.8 production-monitoring flow in one place, then running "
        "an **alert-review exercise** that reuses a v0.7 `explain_feature_family` "
        "summary as reviewer-action evidence, and finally rendering a "
        "**governance-readable summary** that ties the monitoring outputs back to "
        "the Alert lifecycle and the v0.7 monitoring-checklist dimensions.\n"
        "\n"
        "Learning goal: see the two tracks' monitoring behaviour at a glance "
        "(alert volume, precision, recall, capacity utilisation, closure "
        "distribution, score drift), follow one alert's audit chain from "
        "reviewer action back through alert_decision / score to its Banking "
        "relationship and Client-or-User lineage, and read the result as a "
        "governance prompt — not a verdict. **A model should not be judged by "
        "headline accuracy**, and monitoring is a review prompt, not a "
        "certification.\n"
        "\n"
        "> Educational exercise on synthetic data. No real Client, account, or "
        "transaction data; no production-readiness, certification, or legal-"
        "advice claim. The **Client** is the legal customer; the **User** is the "
        "digital login identity."
    ),
    _code(
        "import pandas as pd\n"
        "from sklearn.compose import ColumnTransformer\n"
        "from sklearn.linear_model import LogisticRegression\n"
        "from sklearn.pipeline import Pipeline\n"
        "from sklearn.preprocessing import StandardScaler\n"
        "\n"
        "from banking_fraud_lab import (\n"
        "    build_digital_banking_features,\n"
        "    build_learner_facing_views,\n"
        "    build_model_documentation,\n"
        "    build_monitoring_checklist,\n"
        "    build_private_banking_features,\n"
        "    concentrate_false_positives,\n"
        "    evaluate_alert_scores,\n"
        "    generate_digital_fraud_scenarios_world,\n"
        "    generate_private_banking_transaction_fraud_world,\n"
        "    recommend_lowest_cost_threshold,\n"
        ")\n"
        "from banking_fraud_lab.features import (\n"
        "    DIGITAL_BANKING_FEATURE_FAMILIES,\n"
        "    PRIVATE_BANKING_FEATURE_FAMILIES,\n"
        ")\n"
        "from banking_fraud_lab.interpretability.explanations import (\n"
        "    explain_feature_family,\n"
        ")\n"
        "from banking_fraud_lab.interpretability.spec import (\n"
        "    PB_HIGH_VALUE_EXPLANATION,\n"
        ")\n"
        "from banking_fraud_lab.monitoring import (\n"
        "    check_score_drift,\n"
        "    decide_alerts,\n"
        "    record_reviewer_action,\n"
        "    run_batch_scoring,\n"
        "    summarise_alert_operations,\n"
        ")\n"
        "from banking_fraud_lab.schema import PROTECTED_SCENARIO_ANSWER_KEYS\n"
        "\n"
        "pd.set_option(\"display.max_columns\", 40)"
    ),
    _md(
        "## Build Both Tracks' Supervised Baselines\n"
        "\n"
        "Reproduce the two fitted baselines exactly as in the v0.8 Alpine Crest "
        "and NovaBank monitoring notebooks, so the comparison below starts from "
        "the same reproducible score on each track. Each track keeps its own "
        "model frame, fitted model, numeric feature columns, alert-score frame, "
        "and learner-facing tables in clearly-named variables so the two flows "
        "never collide."
    ),
    _code(
        "def _numeric_columns(frame: pd.DataFrame, families) -> list[str]:\n"
        "    output_columns = [\n"
        "        column\n"
        "        for spec in families\n"
        "        for column in spec.output_columns\n"
        "    ]\n"
        "    return [\n"
        "        column\n"
        "        for column in output_columns\n"
        "        if column in frame.columns and pd.api.types.is_numeric_dtype(frame[column])\n"
        "    ]\n"
        "\n"
        "\n"
        "def _fit_baseline(model_frame: pd.DataFrame, numeric_columns: list[str]) -> Pipeline:\n"
        "    preprocess = ColumnTransformer(\n"
        "        [(\"numeric\", StandardScaler(), numeric_columns)],\n"
        "        remainder=\"drop\",\n"
        "    )\n"
        "    model = Pipeline(\n"
        "        [\n"
        "            (\"preprocess\", preprocess),\n"
        "            (\n"
        "                \"model\",\n"
        "                LogisticRegression(\n"
        "                    random_state=42,\n"
        "                    solver=\"lbfgs\",\n"
        "                    max_iter=1000,\n"
        "                    class_weight=\"balanced\",\n"
        "                ),\n"
        "            ),\n"
        "        ]\n"
        "    )\n"
        "    target = model_frame[\"confirmed_fraud\"].astype(bool)\n"
        "    model.fit(model_frame[numeric_columns], target)\n"
        "    return model\n"
        "\n"
        "\n"
        "# --- Alpine Crest Private Bank (private-banking track) -------------------\n"
        "pb_tables = generate_private_banking_transaction_fraud_world(\n"
        "    seed=42, scenario_prevalence=0.2\n"
        ")\n"
        "pb_learner = build_learner_facing_views(pb_tables)\n"
        "assert PROTECTED_SCENARIO_ANSWER_KEYS in pb_tables\n"
        "assert PROTECTED_SCENARIO_ANSWER_KEYS not in pb_learner\n"
        "pb_feature_frame = build_private_banking_features(pb_learner)\n"
        "pb_model_frame = (\n"
        "    pb_learner[\"cases\"]\n"
        "    .merge(\n"
        "        pb_learner[\"alerts\"]\n"
        "        [\n"
        "            [\n"
        "                \"alert_id\",\n"
        "                \"alert_type\",\n"
        "                \"severity\",\n"
        "                \"reason\",\n"
        "                \"generated_at\",\n"
        "                \"alert_status\",\n"
        "            ]\n"
        "        ],\n"
        "        on=\"alert_id\",\n"
        "        how=\"inner\",\n"
        "    )\n"
        "    .merge(\n"
        "        pb_learner[\"case_outcomes\"][[\"case_id\", \"confirmed_fraud\", \"loss_amount_chf\"]],\n"
        "        on=\"case_id\",\n"
        "        how=\"inner\",\n"
        "    )\n"
        "    .merge(\n"
        "        pb_feature_frame,\n"
        "        on=[\"transaction_id\", \"banking_relationship_id\"],\n"
        "        how=\"inner\",\n"
        "    )\n"
        ")\n"
        "assert pb_model_frame[\"confirmed_fraud\"].nunique() == 2\n"
        "pb_numeric_columns = _numeric_columns(pb_model_frame, PRIVATE_BANKING_FEATURE_FAMILIES)\n"
        "pb_model = _fit_baseline(pb_model_frame, pb_numeric_columns)\n"
        "pb_model_frame = pb_model_frame.assign(\n"
        "    score=pb_model.predict_proba(pb_model_frame[pb_numeric_columns])[:, 1].round(6)\n"
        ")\n"
        "pb_alert_scores = pd.DataFrame(\n"
        "    {\"alert_id\": pb_model_frame[\"alert_id\"], \"score\": pb_model_frame[\"score\"]}\n"
        ")\n"
        "\n"
        "# --- NovaBank Digital (digital-banking track) ----------------------------\n"
        "db_tables = generate_digital_fraud_scenarios_world(\n"
        "    seed=42, scale=\"small\", scenario_prevalence=0.5, noisy_outcome_rate=0.3\n"
        ")\n"
        "db_learner = build_learner_facing_views(db_tables)\n"
        "assert PROTECTED_SCENARIO_ANSWER_KEYS in db_tables\n"
        "assert PROTECTED_SCENARIO_ANSWER_KEYS not in db_learner\n"
        "db_feature_frame = build_digital_banking_features(db_learner)\n"
        "db_model_frame = (\n"
        "    db_learner[\"cases\"][[\"case_id\", \"alert_id\", \"transaction_id\"]]\n"
        "    .merge(\n"
        "        db_learner[\"alerts\"]\n"
        "        [\n"
        "            [\n"
        "                \"alert_id\",\n"
        "                \"alert_type\",\n"
        "                \"severity\",\n"
        "                \"reason\",\n"
        "                \"generated_at\",\n"
        "                \"alert_status\",\n"
        "                \"banking_relationship_id\",\n"
        "                \"user_id\",\n"
        "            ]\n"
        "        ],\n"
        "        on=\"alert_id\",\n"
        "        how=\"inner\",\n"
        "        validate=\"one_to_one\",\n"
        "    )\n"
        "    .merge(\n"
        "        db_learner[\"case_outcomes\"][[\"case_id\", \"confirmed_fraud\", \"loss_amount_chf\"]],\n"
        "        on=\"case_id\",\n"
        "        how=\"inner\",\n"
        "        validate=\"one_to_one\",\n"
        "    )\n"
        "    .merge(db_feature_frame, on=\"transaction_id\", how=\"inner\", validate=\"one_to_one\")\n"
        ")\n"
        "assert db_model_frame[\"confirmed_fraud\"].nunique() == 2\n"
        "db_numeric_columns = _numeric_columns(db_model_frame, DIGITAL_BANKING_FEATURE_FAMILIES)\n"
        "db_model = _fit_baseline(db_model_frame, db_numeric_columns)\n"
        "db_model_frame = db_model_frame.assign(\n"
        "    score=db_model.predict_proba(db_model_frame[db_numeric_columns])[:, 1].round(6)\n"
        ")\n"
        "db_alert_scores = pd.DataFrame(\n"
        "    {\"alert_id\": db_model_frame[\"alert_id\"], \"score\": db_model_frame[\"score\"]}\n"
        ")\n"
        "\n"
        "track_inputs = pd.DataFrame(\n"
        "    [\n"
        "        {\n"
        "            \"institution\": \"Alpine Crest Private Bank\",\n"
        "            \"track\": \"private_banking\",\n"
        "            \"detection_pattern\": \"pb_high_value_movement\",\n"
        "            \"cases\": len(pb_model_frame),\n"
        "            \"features\": len(pb_numeric_columns),\n"
        "        },\n"
        "        {\n"
        "            \"institution\": \"NovaBank Digital\",\n"
        "            \"track\": \"digital_banking\",\n"
        "            \"detection_pattern\": \"digital_scam_to_mule\",\n"
        "            \"cases\": len(db_model_frame),\n"
        "            \"features\": len(db_numeric_columns),\n"
        "        },\n"
        "    ]\n"
        ")\n"
        "track_inputs"
    ),
    _md(
        "## Run Both Tracks' Monitoring Flow\n"
        "\n"
        "For each track: source the threshold from the v0.7 cost-aware "
        "recommender, run batch scoring, decide alerts, summarise operations with "
        "a reused `evaluate_alert_scores` result, and run a score-drift check. "
        "Each track's monitoring artifacts (batch, decisions, operations summary, "
        "drift result) live in its own variable so the comparison below can cite "
        "them directly."
    ),
    _code(
        "def _threshold_for(model_frame: pd.DataFrame, case_outcomes: pd.DataFrame) -> float:\n"
        "    alert_scores = pd.DataFrame(\n"
        "        {\"alert_id\": model_frame[\"alert_id\"], \"score\": model_frame[\"score\"]}\n"
        "    )\n"
        "    recommendation = recommend_lowest_cost_threshold(\n"
        "        cases=model_frame[[\"case_id\", \"alert_id\"]],\n"
        "        case_outcomes=case_outcomes,\n"
        "        alert_scores=alert_scores,\n"
        "        candidate_thresholds=(0.25, 0.5, 0.75),\n"
        "        alert_capacities=(5, 10, 25),\n"
        "        investigation_cost_chf=75.0,\n"
        "        false_positive_cost_chf=25.0,\n"
        "        missed_fraud_cost_chf=1_000.0,\n"
        "    )\n"
        "    return float(recommendation[\"recommended_threshold\"])\n"
        "\n"
        "\n"
        "def _monitor(model_frame: pd.DataFrame, case_outcomes: pd.DataFrame, learner_tables: dict, *, detection_pattern_id: str, scorer: str, score_lineage: list[str]) -> dict:\n"
        "    alert_scores = pd.DataFrame(\n"
        "        {\"alert_id\": model_frame[\"alert_id\"], \"score\": model_frame[\"score\"]}\n"
        "    )\n"
        "    threshold = _threshold_for(model_frame, case_outcomes)\n"
        "    scored_frame = model_frame[score_lineage].copy()\n"
        "    batch = run_batch_scoring(\n"
        "        scored_frame,\n"
        "        detection_pattern_id=detection_pattern_id,\n"
        "        threshold=threshold,\n"
        "        scorer=scorer,\n"
        "        score_version=\"0.8.0\",\n"
        "        evidence_ref=\"v0.7 recommend_lowest_cost_threshold\",\n"
        "    )\n"
        "    threshold_id = str(batch.threshold_rows[\"threshold_id\"].iloc[0])\n"
        "    decisions = decide_alerts(\n"
        "        batch.score_rows,\n"
        "        threshold=threshold,\n"
        "        threshold_id=threshold_id,\n"
        "    )\n"
        "    operations_input = decisions.alert_decision_rows.merge(\n"
        "        learner_tables[\"alerts\"][[\"alert_id\", \"alert_status\"]],\n"
        "        on=\"alert_id\",\n"
        "        how=\"inner\",\n"
        "        validate=\"many_to_one\",\n"
        "    )\n"
        "    operations_input[\"institution_name\"] = model_frame.attrs.get(\n"
        "        \"institution\", \"\"\n"
        "    )\n"
        "    evaluation = evaluate_alert_scores(\n"
        "        cases=model_frame[[\"case_id\", \"alert_id\"]],\n"
        "        case_outcomes=case_outcomes,\n"
        "        alert_scores=alert_scores,\n"
        "        thresholds=(threshold,),\n"
        "        alert_capacity=10,\n"
        "        investigation_cost_chf=75.0,\n"
        "        false_positive_cost_chf=25.0,\n"
        "        missed_fraud_cost_chf=1_000.0,\n"
        "    )\n"
        "    fp_concentration = concentrate_false_positives(\n"
        "        cases=model_frame[[\"case_id\", \"alert_id\"]],\n"
        "        case_outcomes=case_outcomes,\n"
        "        alert_scores=alert_scores,\n"
        "        threshold=threshold,\n"
        "        alerts=learner_tables[\"alerts\"],\n"
        "    )\n"
        "    operations = summarise_alert_operations(\n"
        "        operations_input,\n"
        "        alert_capacity=10,\n"
        "        evaluation=evaluation,\n"
        "    )\n"
        "    reference_scores = batch.score_rows[\"score\"]\n"
        "    review_scores = (reference_scores + 0.2).clip(upper=1.0)\n"
        "    drift = check_score_drift(reference_scores, review_scores, tolerance=0.05)\n"
        "    return {\n"
        "        \"threshold\": threshold,\n"
        "        \"batch\": batch,\n"
        "        \"decisions\": decisions,\n"
        "        \"operations\": operations,\n"
        "        \"evaluation\": evaluation,\n"
        "        \"drift\": drift,\n"
        "        \"fp_concentration\": fp_concentration,\n"
        "    }\n"
        "\n"
        "\n"
        "pb_model_frame.attrs[\"institution\"] = \"Alpine Crest Private Bank\"\n"
        "db_model_frame.attrs[\"institution\"] = \"NovaBank Digital\"\n"
        "\n"
        "pb_flow = _monitor(\n"
        "    pb_model_frame,\n"
        "    pb_learner[\"case_outcomes\"],\n"
        "    pb_learner,\n"
        "    detection_pattern_id=\"pb_high_value_movement\",\n"
        "    scorer=\"alpine-crest-logreg\",\n"
        "    score_lineage=[\"score\", \"banking_relationship_id\", \"transaction_id\", \"alert_id\"],\n"
        ")\n"
        "db_flow = _monitor(\n"
        "    db_model_frame,\n"
        "    db_learner[\"case_outcomes\"],\n"
        "    db_learner,\n"
        "    detection_pattern_id=\"digital_scam_to_mule\",\n"
        "    scorer=\"novabank-logreg\",\n"
        "    score_lineage=[\"score\", \"banking_relationship_id\", \"transaction_id\", \"alert_id\", \"user_id\"],\n"
        ")\n"
        "\n"
        "flow_overview = pd.DataFrame(\n"
        "    [\n"
        "        {\n"
        "            \"institution\": \"Alpine Crest Private Bank\",\n"
        "            \"threshold\": pb_flow[\"threshold\"],\n"
        "            \"score_rows\": len(pb_flow[\"batch\"].score_rows),\n"
        "            \"alert_decisions\": len(pb_flow[\"decisions\"].alert_decision_rows),\n"
        "        },\n"
        "        {\n"
        "            \"institution\": \"NovaBank Digital\",\n"
        "            \"threshold\": db_flow[\"threshold\"],\n"
        "            \"score_rows\": len(db_flow[\"batch\"].score_rows),\n"
        "            \"alert_decisions\": len(db_flow[\"decisions\"].alert_decision_rows),\n"
        "        },\n"
        "    ]\n"
        ")\n"
        "flow_overview"
    ),
    _md(
        "## Side-By-Side Track Comparison\n"
        "\n"
        "One row per track so the monitoring differences are visible at a glance: "
        "alert volume, precision and recall (reused from each track's "
        "`evaluate_alert_scores` summary via `summarise_alert_operations`), "
        "capacity utilisation against a shared alert capacity of 10, the top "
        "closure status by Alert lifecycle state, and a drift flag (whether the "
        "controlled review window's mean shift exceeded the 0.05 tolerance). The "
        "comparison is a review prompt — differences between tracks reflect "
        "different Detection patterns and data-generating processes on synthetic "
        "data, not a ranking."
    ),
    _code(
        "def _top_closure(operations: dict) -> str:\n"
        "    closure = operations.get(\"closure_distribution\") or {}\n"
        "    if not closure:\n"
        "        return \"\"\n"
        "    return max(closure, key=closure.get)\n"
        "\n"
        "\n"
        "comparison = pd.DataFrame(\n"
        "    [\n"
        "        {\n"
        "            \"institution\": \"Alpine Crest Private Bank\",\n"
        "            \"track\": \"private_banking\",\n"
        "            \"detection_pattern\": \"pb_high_value_movement\",\n"
        "            \"alert_volume\": pb_flow[\"operations\"][\"alert_volume\"],\n"
        "            \"precision\": pb_flow[\"operations\"][\"precision\"],\n"
        "            \"recall\": pb_flow[\"operations\"][\"recall\"],\n"
        "            \"capacity_utilization\": pb_flow[\"operations\"][\"capacity_utilization\"],\n"
        "            \"top_closure_status\": _top_closure(pb_flow[\"operations\"]),\n"
        "            \"score_drift_flag\": pb_flow[\"drift\"].drifted,\n"
        "            \"score_drift_shift\": pb_flow[\"drift\"].mean_shift,\n"
        "        },\n"
        "        {\n"
        "            \"institution\": \"NovaBank Digital\",\n"
        "            \"track\": \"digital_banking\",\n"
        "            \"detection_pattern\": \"digital_scam_to_mule\",\n"
        "            \"alert_volume\": db_flow[\"operations\"][\"alert_volume\"],\n"
        "            \"precision\": db_flow[\"operations\"][\"precision\"],\n"
        "            \"recall\": db_flow[\"operations\"][\"recall\"],\n"
        "            \"capacity_utilization\": db_flow[\"operations\"][\"capacity_utilization\"],\n"
        "            \"top_closure_status\": _top_closure(db_flow[\"operations\"]),\n"
        "            \"score_drift_flag\": db_flow[\"drift\"].drifted,\n"
        "            \"score_drift_shift\": db_flow[\"drift\"].mean_shift,\n"
        "        },\n"
        "    ]\n"
        ")\n"
        "comparison"
    ),
    _md(
        "## Alert-Review Exercise: Reuse A v0.7 Explanation As Evidence\n"
        "\n"
        "Pick the highest-score Alpine Crest alert decision, build a v0.7 "
        "`explain_feature_family` summary for the `pb_high_value_movement` family "
        "as reviewer-action evidence, record a reviewer action carrying that "
        "evidence, and then walk the resulting audit chain backwards: from the "
        "`AUDIT_REVIEWER_ACTION_RECORDED` audit event, to the reviewer action, to "
        "the alert decision, to the score, and out to the Banking relationship / "
        "Client-or-User / Detection-pattern lineage. The same pattern works for "
        "any track; we exercise it on the Alpine Crest side here."
    ),
    _code(
        "# v0.7 explanation summary reused as the alert-review evidence.\n"
        "# explain_feature_family projects the frame to the family's columns and\n"
        "# scores a model on them, so fit a family-scoped model on just the\n"
        "# PB_HIGH_VALUE_EXPLANATION columns (the same surface a v0.7 per-family\n"
        "# explanation notebook would build), then reuse it as reviewer evidence.\n"
        "pb_family_columns = list(PB_HIGH_VALUE_EXPLANATION.feature_columns)\n"
        "pb_family_model = _fit_baseline(pb_model_frame, pb_family_columns)\n"
        "pb_explanation = explain_feature_family(\n"
        "    pb_family_model,\n"
        "    pb_model_frame,\n"
        "    PB_HIGH_VALUE_EXPLANATION,\n"
        ")\n"
        "pb_top_feature = str(\n"
        "    pb_explanation[\"feature_importance\"]\n"
        "    .sort_values(\"native_importance\", ascending=False)\n"
        "    .iloc[0][\"feature\"]\n"
        ")\n"
        "pb_top_importance = float(\n"
        "    pb_explanation[\"feature_importance\"].set_index(\"feature\")\n"
        "    .loc[pb_top_feature, \"native_importance\"]\n"
        ")\n"
        "\n"
        "# Pick the highest-score Alpine Crest alert decision to review. The\n"
        "# alert_decision rows already carry alert_id lineage; merge in the score\n"
        "# value (renamed) to avoid a column-name collision with that lineage.\n"
        "pb_decision_rows = pb_flow[\"decisions\"].alert_decision_rows.merge(\n"
        "    pb_flow[\"batch\"].score_rows[[\"score_id\", \"score\"]].rename(\n"
        "        columns={\"score\": \"score_value\"}\n"
        "    ),\n"
        "    on=\"score_id\",\n"
        "    how=\"inner\",\n"
        "    validate=\"one_to_one\",\n"
        ")\n"
        "review_decision = pb_decision_rows.sort_values(\"score_value\", ascending=False).iloc[0]\n"
        "review_alert_id = str(review_decision[\"alert_id\"])\n"
        "\n"
        "# Record a reviewer action whose evidence is the v0.7 explanation summary.\n"
        "review_frame = pd.DataFrame([review_decision.to_dict()])\n"
        "reviewer_action = record_reviewer_action(\n"
        "    review_frame,\n"
        "    reviewer=\"rm-analyst\",\n"
        "    action=\"confirm\",\n"
        "    rationale=\"Reviewed against high-value movement playbook.\",\n"
        "    evidence={\n"
        "        \"detection_pattern_id\": \"pb_high_value_movement\",\n"
        "        \"explanation_family_id\": pb_explanation[\"family_id\"],\n"
        "        \"top_feature\": pb_top_feature,\n"
        "        \"top_native_importance\": pb_top_importance,\n"
        "        \"reviewed_alert_id\": review_alert_id,\n"
        "    },\n"
        ")\n"
        "reviewer_action.reviewer_action_rows[\n"
        "    [\"reviewer_action_id\", \"alert_decision_id\", \"reviewer\", \"action\", \"evidence\"]\n"
        "]"
    ),
    _code(
        "# Lineage walk: audit_event (reviewer) -> reviewer_action -> alert_decision\n"
        "# -> score -> Banking relationship / Client-or-User / Detection pattern.\n"
        "ra_row = reviewer_action.reviewer_action_rows.iloc[0]\n"
        "ra_audit = reviewer_action.audit_rows.iloc[0]\n"
        "decision_lookup = pb_flow[\"decisions\"].alert_decision_rows.set_index(\n"
        "    \"alert_decision_id\"\n"
        ")\n"
        "decision_row = decision_lookup.loc[str(ra_row[\"alert_decision_id\"])]\n"
        "score_lookup = pb_flow[\"batch\"].score_rows.set_index(\"score_id\")\n"
        "score_row = score_lookup.loc[str(decision_row[\"score_id\"])]\n"
        "alert_lookup = pb_learner[\"alerts\"].set_index(\"alert_id\")\n"
        "alert_row = alert_lookup.loc[str(score_row[\"alert_id\"])]\n"
        "\n"
        "lineage = pd.DataFrame(\n"
        "    [\n"
        "        {\n"
        "            \"step\": \"audit_event\",\n"
        "            \"id\": str(ra_audit[\"audit_event_id\"]),\n"
        "            \"type\": str(ra_audit[\"audit_event_type\"]),\n"
        "        },\n"
        "        {\n"
        "            \"step\": \"reviewer_action\",\n"
        "            \"id\": str(ra_row[\"reviewer_action_id\"]),\n"
        "            \"type\": f\"{ra_row['reviewer']} {ra_row['action']}\",\n"
        "        },\n"
        "        {\n"
        "            \"step\": \"alert_decision\",\n"
        "            \"id\": str(ra_row[\"alert_decision_id\"]),\n"
        "            \"type\": str(decision_row[\"decision\"]),\n"
        "        },\n"
        "        {\n"
        "            \"step\": \"score\",\n"
        "            \"id\": str(decision_row[\"score_id\"]),\n"
        "            \"type\": f\"score {float(score_row['score']):.4f}\",\n"
        "        },\n"
        "        {\n"
        "            \"step\": \"alert (lifecycle)\",\n"
        "            \"id\": str(score_row[\"alert_id\"]),\n"
        "            \"type\": str(alert_row.get(\"alert_status\", \"\")),\n"
        "        },\n"
        "        {\n"
        "            \"step\": \"Banking relationship\",\n"
        "            \"id\": str(decision_row[\"banking_relationship_id\"]),\n"
        "            \"type\": \"banking_relationship\",\n"
        "        },\n"
        "        {\n"
        "            \"step\": \"Detection pattern\",\n"
        "            \"id\": str(decision_row[\"detection_pattern_id\"]),\n"
        "            \"type\": \"detection_pattern\",\n"
        "        },\n"
        "    ]\n"
        ")\n"
        "lineage"
    ),
    _md(
        "## Governance-Readable Summary\n"
        "\n"
        "Reuse the v0.7 governance framing — `build_model_documentation` and "
        "`build_monitoring_checklist` for the Alpine Crest track — alongside the "
        "monitoring outputs above, and tie them back to the Alert lifecycle. The "
        "monitoring checklist dimensions (`score_drift`, `metric_stability`, "
        "`false_positive_concentration`, `segment_review`, `data_quality`) are the "
        "v0.7 vocabulary the v0.8 monitoring builders feed; the governance summary "
        "below reads each track's monitoring outputs onto those dimensions so a "
        "reviewer sees what to re-review, not what is 'good'."
    ),
    _code(
        "pb_documentation = build_model_documentation(\n"
        "    pb_model,\n"
        "    institution=\"Alpine Crest Private Bank\",\n"
        "    detection_pattern_id=\"pb_high_value_movement\",\n"
        "    feature_columns=pb_numeric_columns,\n"
        "    model_frame=pb_model_frame,\n"
        "    seed=42,\n"
        "    cost_parameters={\n"
        "        \"investigation_cost_chf\": 75.0,\n"
        "        \"false_positive_cost_chf\": 25.0,\n"
        "        \"missed_fraud_cost_chf\": 1_000.0,\n"
        "    },\n"
        ")\n"
        "pb_checklist = build_monitoring_checklist(\n"
        "    institution=\"Alpine Crest Private Bank\",\n"
        "    detection_pattern_id=\"pb_high_value_movement\",\n"
        "    evaluation=pb_flow[\"evaluation\"],\n"
        ")\n"
        "\n"
        "documentation_index = pd.DataFrame(\n"
        "    [\n"
        "        {\n"
        "            \"institution\": \"Alpine Crest Private Bank\",\n"
        "            \"sections_filled\": len(pb_documentation[\"sections\"]),\n"
        "            \"estimator\": pb_documentation[\"metadata\"][\"estimator_summary\"],\n"
        "        }\n"
        "    ]\n"
        ")\n"
        "documentation_index"
    ),
    _code(
        "# Tie the monitoring outputs back onto the v0.7 checklist dimensions and the\n"
        "# Alert lifecycle steps. Each row names the dimension, the lifecycle step the\n"
        "# monitoring output speaks to, the computed signal, and the review prompt.\n"
        "def _fp_concentration_signal(concentration: pd.DataFrame) -> str:\n"
        "    if concentration.empty:\n"
        "        return \"no false positives above threshold\"\n"
        "    top_share = float(concentration[\"false_positive_share\"].iloc[0])\n"
        "    return f\"top segment carries {top_share:.1%} of false positives\"\n"
        "\n"
        "\n"
        "governance_table = pd.DataFrame(\n"
        "    [\n"
        "        {\n"
        "            \"dimension\": \"score_drift\",\n"
        "            \"lifecycle_step\": \"score\",\n"
        "            \"alpine_crest_signal\": pb_flow[\"drift\"].drifted,\n"
        "            \"novabank_signal\": db_flow[\"drift\"].drifted,\n"
        "            \"review_prompt\": \"Re-check the score window when flagged; drift is a review prompt, not a verdict.\",\n"
        "        },\n"
        "        {\n"
        "            \"dimension\": \"metric_stability\",\n"
        "            \"lifecycle_step\": \"alert_decision\",\n"
        "            \"alpine_crest_signal\": (\n"
        "                f\"precision {pb_flow['operations']['precision']:.2f}, \"\n"
        "                f\"recall {pb_flow['operations']['recall']:.2f}\"\n"
        "            ),\n"
        "            \"novabank_signal\": (\n"
        "                f\"precision {db_flow['operations']['precision']:.2f}, \"\n"
        "                f\"recall {db_flow['operations']['recall']:.2f}\"\n"
        "            ),\n"
        "            \"review_prompt\": \"Precision/recall are reused from evaluate_alert_scores; review across thresholds before acting.\",\n"
        "        },\n"
        "        {\n"
        "            \"dimension\": \"false_positive_concentration\",\n"
        "            \"lifecycle_step\": \"alert_decision\",\n"
        "            \"alpine_crest_signal\": _fp_concentration_signal(\n"
        "                pb_flow[\"fp_concentration\"]\n"
        "            ),\n"
        "            \"novabank_signal\": _fp_concentration_signal(\n"
        "                db_flow[\"fp_concentration\"]\n"
        "            ),\n"
        "            \"review_prompt\": \"False-positive concentration is a segment-level review cue from concentrate_false_positives, not a verdict; re-scan concentrated segments before confirming.\",\n"
        "        },\n"
        "        {\n"
        "            \"dimension\": \"segment_review\",\n"
        "            \"lifecycle_step\": \"alert_decision\",\n"
        "            \"alpine_crest_signal\": (\n"
        "                f\"capacity_utilization {pb_flow['operations']['capacity_utilization']:.2f}\"\n"
        "            ),\n"
        "            \"novabank_signal\": (\n"
        "                f\"capacity_utilization {db_flow['operations']['capacity_utilization']:.2f}\"\n"
        "            ),\n"
        "            \"review_prompt\": \"Capacity utilisation is a review-burden cue, not a fairness verdict.\",\n"
        "        },\n"
        "        {\n"
        "            \"dimension\": \"data_quality\",\n"
        "            \"lifecycle_step\": \"reviewer_action\",\n"
        "            \"alpine_crest_signal\": \"required monitoring columns present\",\n"
        "            \"novabank_signal\": \"required monitoring columns present\",\n"
        "            \"review_prompt\": \"Re-confirm input completeness each window; degraded inputs distort scores silently.\",\n"
        "        },\n"
        "    ]\n"
        ")\n"
        "governance_table"
    ),
    _code(
        "# Stakeholder-readable memo text (educational draft; no certification claim).\n"
        "pb_top_closure = _top_closure(pb_flow[\"operations\"])\n"
        "db_top_closure = _top_closure(db_flow[\"operations\"])\n"
        "\n"
        "memo = [\n"
        "    \"# Alert Review And Governance Summary (Educational Draft)\",\n"
        "    \"\",\n"
        "    \"Synthesises the two tracks' v0.8 monitoring outputs and the v0.7 explanation reused as alert-review evidence.\",\n"
        "    \"\",\n"
        "    \"## Alpine Crest Private Bank - private_banking (pb_high_value_movement)\",\n"
        "    f\"- Threshold {pb_flow['threshold']:.2f}; alert volume \"\n"
        "    f\"{pb_flow['operations']['alert_volume']} against a capacity of \"\n"
        "    f\"{pb_flow['operations']['alert_capacity']} \"\n"
        "    f\"(capacity utilisation {pb_flow['operations']['capacity_utilization']:.2f}).\",\n"
        "    f\"- Precision {pb_flow['operations']['precision']:.2f}, recall \"\n"
        "    f\"{pb_flow['operations']['recall']:.2f} (reused from evaluate_alert_scores).\",\n"
        "    f\"- Alert lifecycle closure skews to '{pb_top_closure}'. Score drift flagged \"\n"
        "    f\"for review: {pb_flow['drift'].drifted} \"\n"
        "    f\"(mean shift {pb_flow['drift'].mean_shift:.4f}).\",\n"
        "    f\"- Reviewed alert {review_alert_id}: reviewer-action evidence was the v0.7 \"\n"
        "    f\"'{pb_explanation['family_id']}' summary, top feature '{pb_top_feature}' \"\n"
        "    f\"(native importance {pb_top_importance:.4f}).\",\n"
        "    \"- Model documentation: \"\n"
        "    f\"{len(pb_documentation['sections'])} sections filled for estimator \"\n"
        "    f\"{pb_documentation['metadata']['estimator_summary']}.\",\n"
        "    \"\",\n"
        "    \"## NovaBank Digital - digital_banking (digital_scam_to_mule)\",\n"
        "    f\"- Threshold {db_flow['threshold']:.2f}; alert volume \"\n"
        "    f\"{db_flow['operations']['alert_volume']} against a capacity of \"\n"
        "    f\"{db_flow['operations']['alert_capacity']} \"\n"
        "    f\"(capacity utilisation {db_flow['operations']['capacity_utilization']:.2f}).\",\n"
        "    f\"- Precision {db_flow['operations']['precision']:.2f}, recall \"\n"
        "    f\"{db_flow['operations']['recall']:.2f} (reused from evaluate_alert_scores).\",\n"
        "    f\"- Alert lifecycle closure skews to '{db_top_closure}'. Score drift flagged \"\n"
        "    f\"for review: {db_flow['drift'].drifted} \"\n"
        "    f\"(mean shift {db_flow['drift'].mean_shift:.4f}).\",\n"
        "    \"\",\n"
        "    \"## Alert lifecycle mapping\",\n"
        "    \"- score -> run_batch_scoring + check_score_drift (score_drift dimension).\",\n"
        "    \"- alert_decision -> decide_alerts + summarise_alert_operations (metric_stability, segment_review).\",\n"
        "    \"- reviewer_action -> record_reviewer_action with a v0.7 explanation as evidence (data_quality + lineage).\",\n"
        "    \"- closure -> Alert lifecycle status distribution from the inspectable queue.\",\n"
        "    \"\",\n"
        "    \"Limitations: deterministic synthetic data, sparse fraud labels, operational alert outcomes. \"\n"
        "    \"Explanations are inspection aids, not proof of correctness. A model should not be judged by headline accuracy.\",\n"
        "]\n"
        "memo_text = \"\\n\".join(memo)\n"
        "print(memo_text)"
    ),
    _md(
        "## Governance-Language Guardrail\n"
        "\n"
        "Confirm the summary carries no certification or legal-advice claims and "
        "keeps the limitation-aware framing visible. The repository stays private; "
        "this notebook adds no public-release language."
    ),
    _code(
        "# Forbidden governance phrases are assembled from parts so the guardrail\n"
        "# source itself does not contain them as contiguous substrings.\n"
        "forbidden_phrases = [\n"
        "    \"is\" + \" certified\",\n"
        "    \"legal\" + \" advice\",\n"
        "    \"production\" + \"-ready\",\n"
        "    \"compliance\" + \" requirement\",\n"
        "]\n"
        "for forbidden in forbidden_phrases:\n"
        "    assert forbidden not in memo_text.lower(), f\"memo contains forbidden term: {forbidden!r}\"\n"
        "assert \"should not be judged by headline accuracy\" in memo_text\n"
        "assert \"Alpine Crest Private Bank\" in memo_text\n"
        "assert \"NovaBank Digital\" in memo_text\n"
        "print(\"Governance-language guardrail passed: no certification/legal-advice claims; \"\n"
        "      \"limitation-aware framing visible; both institutions named.\")"
    ),
    _md(
        "## Keep Monitoring Limits Visible\n"
        "\n"
        "Monitoring is a review prompt, not a verdict. The track comparison, the "
        "alert-review lineage, and the governance summary above surface what to "
        "look at — they do not certify either model. Fraud labels are sparse, "
        "alert outcomes are operational decisions, and protected answer keys stay "
        "separate from learner-facing data. A reviewer still has to read the "
        "alert, the explanation, and the case context. **A model should not be "
        "judged by headline accuracy.**"
    ),
]


def build_notebook() -> dict:
    """Assemble the notebook JSON."""
    return {
        "cells": CELLS,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    """Write the notebook to disk under notebooks/08_production_monitoring_patterns/."""
    NOTEBOOK_DIR.mkdir(parents=True, exist_ok=True)
    NOTEBOOK_PATH.write_text(
        json.dumps(build_notebook(), indent=1, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {NOTEBOOK_PATH} ({len(CELLS)} cells)")


if __name__ == "__main__":
    main()
